input_features:
  - name: path
    type: image
    augmentation: True
    preprocessor:
        height: 224
        width: 224
    encoder: 
      type: stacked_cnn
      conv_layers:
        - num_filters: 32
          filter_size: 3
          pool_size: 2
          pool_stride: 2
          conv_norm: batch
        - num_filters: 64
          filter_size: 3
          pool_size: 2
          pool_stride: 2
          dropout: 0.4
          conv_norm: batch
      fc_layers:
        - output_size: 128
          dropout: 0.4
        - output_size: 64
          dropout: 0.4
output_features:
  - name: label
    type: category

preprocessing:
    sample_ratio: 1.0
    oversample_minority: null
    undersample_majority: null
    split:
        type: random
        probabilities:
        - 0.75
        - 0.15
        - 0.1
        
trainer:
    learning_rate: 0.001
    epochs: 100
    early_stop: 25
    regularization_type: l2
    regularization_lambda: 0.01
    