input_features:
  - name: path
    type: image
    encoder: resnet
    preprocessor:
      height: 224
      width: 224
      normalization: imagenet
output_features:
  - name: label
    type: category

training:
  batch_size: 32
  epochs: 10
  metric: loss
  patience: 5

pretrained_model:
  type: resnet_v2_50
  pretrained: true
  freeze: true

combiner:
  type: concat
  fc_size: 64
  num_fc_layers: 2