input_features:
  - name: path
    type: image
    encoder: 
        type: stacked_cnn
        conv_layers:
          - out_channels: 64
            padding: same
            conv_norm: batch
            kernel_size: 3
            conv_activation: relu
            pool_function: max
          - out_channels: 128
            kernel_size: 3
            conv_norm: batch
            padding: same
            conv_activation: relu
            pool_function: max
        fc_layers:
          - output_size: 256
            conv_activation: relu
          - output_size: 2
            conv_activation: softmax
output_features:
  - name: label
    type: category

trainer:
  epochs: 10